/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static DB.Db.search;
import static Logger.Log.warning;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author abhi
 */
public class AddNewClassPayment extends javax.swing.JFrame {

    /**
     * Creates new form AddNewClassPayment
     */
    double tot;
    String tId;
    String theme;
    String userId;
    String user;
    Payments p;

    HashMap<String, String> institute = new HashMap<String, String>();

    public AddNewClassPayment(String theme, String userId, String user, Payments p) {
        initComponents();
        this.user = user;
        this.userId = userId;
        this.theme = theme;
        this.p = p;
        teacherLoad();
        tableDesign();
        themeLoad(theme);

        ResultSet rs = search("SELECT * FROM institute");

        try {
            if (rs.next()) {
                institute.put("name", rs.getString("name"));
                institute.put("address", rs.getString("address"));
                institute.put("phone1", rs.getString("phone1"));
                institute.put("phone2", rs.getString("phone2"));
                institute.put("website", rs.getString("website"));
                institute.put("fax", rs.getString("fax"));
                institute.put("thank_msg", rs.getString("thank_msg"));
                institute.put("addmision", rs.getString("addmision"));
                institute.put("to_institute", rs.getString("to_institute"));
                institute.put("path", rs.getString("path"));
                institute.put("noti_pay", rs.getString("noti_pay"));
                institute.put("print_after_pay", rs.getString("print_after_pay"));
                institute.put("noti_leave", rs.getString("noti_leave"));
                institute.put("logo_invoice", rs.getString("logo_invoice"));
                institute.put("noti_exam_results", rs.getString("noti_exam_results"));
                institute.put("print_2_invoice", rs.getString("print_2_invoice"));
                institute.put("noti_register", rs.getString("noti_register"));
                institute.put("noti_class_cancel", rs.getString("noti_class_cancel"));
                institute.put("noti_user_login", rs.getString("noti_user_login"));
                institute.put("print_barcode", rs.getString("print_barcode"));
            }
        } catch (SQLException ex) {
            warning(ex);
            ex.printStackTrace();
        }

    }

    public AddNewClassPayment() {
        initComponents();

        teacherLoad();
        tableDesign();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(72, 52, 212));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW CLASS PAYMENT");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/images/basic/close_window_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "CLASS ID", "CLASS", "STUDENTS ", "STUDENT FEE", "TEACHER FEE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Search");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEACHER ID", "NAME", "NIC", "EMAIL", "CONTACT", "BALANCE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jTable2.setShowVerticalLines(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        jLabel12.setText("records found  ");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("0");

        jLabel14.setText("records found  ");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("0");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Total : Rs.");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("0.00");

        jButton6.setBackground(new java.awt.Color(72, 52, 212));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Complete");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(599, 599, 599)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel14)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        if (evt.getClickCount() == 2) {

            int row = jTable2.getSelectedRow();

            tId = jTable2.getValueAt(row, 0).toString();

            SimpleDateFormat sdf = new SimpleDateFormat("MM");
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy");
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");

            int month = Integer.valueOf(sdf.format(new Date()));

            if (month == 1) {
                month = 12;
            } else {
                month--;
            }

            int year = Integer.parseInt(sdf1.format(new Date()));

            ResultSet search = search("SELECT * FROM class_payment WHERE class_payment.teacher_id = '" + tId + "' && class_payment.month_id = '" + month + "' && class_payment.year = '" + year + "';");

            try {
                if (search.next()) {
                    //if already payied
                    YearMonth thisYearMonth = YearMonth.of(year, month);
                    JOptionPane.showMessageDialog(null, jTable2.getValueAt(row, 1) + "'s " + year + " " + thisYearMonth.getMonth() + " payments are setteled.", "Warning", JOptionPane.WARNING_MESSAGE);

                } else {

                    TableModel model = jTable1.getModel();
                    DefaultTableModel dtm = (DefaultTableModel) model;
                    dtm.setRowCount(0);

                    ResultSet search1 = search("SELECT * FROM class_payment WHERE class_payment.id IN (SELECT MAX(id) FROM class_payment WHERE class_payment.year = '" + year + "' && class_payment.teacher_id = '" + tId + "')");

                    if (search1.next()) { // if teachers already got payments

                        try {
                            ResultSet rs = search("SELECT * FROM class INNER JOIN subject INNER JOIN day WHERE status = '1' && class.subject_id = subject.id && day.id = class.day_id && teacher_id = '" + jTable2.getValueAt(row, 0) + "'");
                            int i = 0;
                            tot = 0.00;
                            jLabel27.setText(String.valueOf(i));
                            jLabel9.setText(String.valueOf(tot));
                            while (rs.next()) {

                                LocalDate currentDate = LocalDate.now();
                                Month m = currentDate.getMonth();

                                String quer1 = "SELECT student_class_card_type.`type`,\n"
                                        + "	COUNT(fees.id) AS `students`,\n"
                                        + "	class.fee AS `fee`\n"
                                        + "\n"
                                        + " FROM student_class\n"
                                        + "\n"
                                        + "INNER JOIN student_class_fees\n"
                                        + "INNER JOIN student_class_card_type\n"
                                        + "INNER JOIN fees\n"
                                        + "INNER JOIN class\n"
                                        + "\n"
                                        + "\n"
                                        + " WHERE class_id = '" + rs.getString("id") + "'\n"
                                        + " && student_class.student_class_card_type_id = student_class_card_type.id\n"
                                        + " && student_class_fees.student_class_id = student_class.id\n"
                                        + " && student_class_fees.fees_id = fees.id\n"
                                        + " && student_class.class_id = class.id\n"
                                        + " && DATE(fees.date) >= '" + search1.getDate("date") + "' and DATE(fees.date)  <= '" + sdf2.format(new Date()) + "'\n"
                                        + " \n"
                                        + "  GROUP BY student_class_card_type.id\n"
                                        + "HAVING COUNT(student_class_card_type.id) >= 1";

                                ResultSet rs1 = search(quer1);

                                while (rs1.next()) {
                                    i++;
                                    Vector<Object> v = new Vector<>();

                                    v.add(String.valueOf(i));
                                    v.add(rs.getString("class.id"));

                                    v.add(rs.getString("subject") + "-" + rs.getString("desc") + "(" + rs.getString("day") + ")");
                                    v.add(rs1.getString("students") + " (" + rs1.getString("type") + ")");

                                    if (rs1.getString("type").equals("Full")) {
                                        v.add(rs1.getString("fee"));
                                        v.add(String.valueOf(Double.valueOf(rs1.getString("fee")) - Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute"))));
                                        v.add(String.valueOf((Double.valueOf(rs1.getString("fee")) - (Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students"))));
                                        tot = tot + ((Double.valueOf(rs1.getString("fee")) - (Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute"))))) * Double.parseDouble(rs1.getString("students"));
                                    }
                                    if (rs1.getString("type").equals("Half")) {
                                        v.add(String.valueOf((Double.parseDouble(rs1.getString("fee")) / 2)));
                                        v.add(String.valueOf((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute")))));
                                        v.add(String.valueOf(((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students"))));
                                        tot = tot + ((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute"))));
                                    }
                                    if (rs1.getString("type").equals("Free")) {
                                        v.add("0.00");
                                        v.add("0.00");
                                        v.add(String.valueOf(0 * Double.parseDouble(rs1.getString("students"))));
                                    }

                                    dtm.addRow(v);

//                        System.out.println(rs1.getString("fee"));
                                }
                                jLabel27.setText(String.valueOf(i));
                                jLabel9.setText(String.valueOf(tot));

                            }

                        } catch (Exception e) {
                            System.out.println(e);
                            warning(e);
                        }
                    } else {
                        // if new teacher getting payments
                        ResultSet search2 = search("SELECT * FROM teacher WHERE id = '" + tId + "'");

                        if (search2.next()) {
                            System.out.println("no already payment");
                            try {
                                ResultSet rs = search("SELECT * FROM class INNER JOIN subject INNER JOIN day WHERE status = '1' && class.subject_id = subject.id && day.id = class.day_id && teacher_id = '" + jTable2.getValueAt(row, 0) + "'");
                                int i = 0;
                                tot = 0.00;
                                jLabel27.setText(String.valueOf(i));
                                jLabel9.setText(String.valueOf(tot));
                                while (rs.next()) {

                                    LocalDate currentDate = LocalDate.now();
                                    Month m = currentDate.getMonth();

                                    String quer1 = "SELECT student_class_card_type.`type`,\n"
                                            + "	COUNT(fees.id) AS `students`,\n"
                                            + "	class.fee AS `fee`\n"
                                            + "\n"
                                            + " FROM student_class\n"
                                            + "\n"
                                            + "INNER JOIN student_class_fees\n"
                                            + "INNER JOIN student_class_card_type\n"
                                            + "INNER JOIN fees\n"
                                            + "INNER JOIN class\n"
                                            + "\n"
                                            + "\n"
                                            + " WHERE class_id = '" + rs.getString("class.id") + "'\n"
                                            + " && student_class.student_class_card_type_id = student_class_card_type.id\n"
                                            + " && student_class_fees.student_class_id = student_class.id\n"
                                            + " && student_class_fees.fees_id = fees.id\n"
                                            + " && student_class.class_id = class.id\n"
                                            + " && DATE(fees.date) >= '" + search2.getString("date_reg") + "' and DATE(fees.date)  <= '" + sdf2.format(new Date()) + "'\n"
                                            + " \n"
                                            + "  GROUP BY student_class_card_type.id\n"
                                            + "HAVING COUNT(student_class_card_type.id) >= 1";

                                    ResultSet rs1 = search(quer1);
                                    System.out.println(search2.getString("date_reg"));
                                    System.out.print(sdf2.format(new Date()));
                                    while (rs1.next()) {
                                        i++;
                                        Vector<Object> v = new Vector<>();

                                        v.add(String.valueOf(i));
                                        v.add(rs.getString("class.id"));

                                        v.add(rs.getString("subject") + "-" + rs.getString("desc") + "(" + rs.getString("day") + ")");
                                        v.add(rs1.getString("students") + " (" + rs1.getString("type") + ")");

                                        if (rs1.getString("type").equals("Full")) {
                                            v.add(rs1.getString("fee"));
                                            v.add(String.valueOf(Double.valueOf(rs1.getString("fee")) - Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute"))));
                                            v.add(String.valueOf((Double.valueOf(rs1.getString("fee")) - (Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students"))));
                                            tot = tot + (Double.valueOf(rs1.getString("fee")) - (Double.parseDouble(rs1.getString("fee")) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students"));
                                        }
                                        if (rs1.getString("type").equals("Half")) {
                                            v.add(String.valueOf((Double.parseDouble(rs1.getString("fee")) / 2)));
                                            v.add(String.valueOf((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute")))));
                                            v.add(String.valueOf(((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students"))));
                                            tot = tot + (((Double.parseDouble(rs1.getString("fee")) / 2) - ((Double.parseDouble(rs1.getString("fee")) / 2) * Double.parseDouble(institute.get("to_institute")))) * Double.parseDouble(rs1.getString("students")));
                                        }
                                        if (rs1.getString("type").equals("Free")) {
                                            v.add("0.00");
                                            v.add("0.00");
                                            v.add(String.valueOf(0 * Double.parseDouble(rs1.getString("students"))));
                                        }

                                        dtm.addRow(v);

//                        System.out.println(rs1.getString("fee"));
                                    }
                                    jLabel27.setText(String.valueOf(i));
                                    jLabel9.setText(String.valueOf(tot));

                                }

                            } catch (Exception e) {
                                System.out.println(e);
                                warning(e);
                            }

                        }

                    }

                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                warning(ex);
            }

        }

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (!jLabel9.getText().equals("0.00") && !jLabel9.getText().equals("0.0")) {

            IssueTeacherPayment itp = new IssueTeacherPayment(tId, this, theme, userId, user);
            itp.jLabel19.setText(String.valueOf(Double.parseDouble(jLabel9.getText())));
            itp.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "NO payments are selected, please select valid payment", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewClassPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewClassPayment().setVisible(true);
            }
        });
    }

    void tableDesign() {
        JTableHeader th = jTable1.getTableHeader();
        JTableHeader th1 = jTable2.getTableHeader();
        Font font = new Font("Century Gothic", Font.PLAIN, 12);
        th.setFont(font);
        th1.setFont(font);
        th.setOpaque(false);
        th1.setOpaque(false);
        Color cb = new Color(45, 52, 54);
        Color cf = new Color(241, 242, 246);
        th.setForeground(cf);
        th1.setForeground(cf);
        th.setBackground(cb);
        th1.setBackground(cb);
    }

    void teacherLoad() {

        TableModel model = jTable2.getModel();
        DefaultTableModel dtm = (DefaultTableModel) model;
        dtm.setRowCount(0);

        try {
            ResultSet rs = search("SELECT * FROM teacher WHERE status = '1'");
            int i = 1;
            while (rs.next()) {
                Vector<String> v = new Vector<>();

                v.add(rs.getString("id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("email"));
                v.add(rs.getString("contact1") + " / " + rs.getString("contact2"));
                v.add(rs.getString("balance"));

                dtm.addRow(v);

                jLabel26.setText(String.valueOf(i));
                i++;
            }

        } catch (Exception e) {
            System.out.println(e);
            warning(e);
        }

    }

    void themeLoad(String theme) {

        jPanel2.setBackground(new Color(Integer.parseInt(theme.split(",")[0]), Integer.parseInt(theme.split(",")[1]), Integer.parseInt(theme.split(",")[2])));
        jButton6.setBackground(new Color(Integer.parseInt(theme.split(",")[0]), Integer.parseInt(theme.split(",")[1]), Integer.parseInt(theme.split(",")[2])));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
